data:
  root: /home/rahim/exp/Data/Agriculture_pest_dataset
  img_size: 224
  resize: 256
  train_frac: 0.70
  val_frac: 0.15
  test_frac: 0.15
  batch_size: 64
  num_workers: 4
  balance_seed: 42
system:
  device: "cuda"
  seed: 42
  fp16: false
train:
  epochs: 10
  lr: 0.0005
  weight_decay: 0.0001
  freeze_backbone: true
  label_smoothing: 0.0
  warmup_epochs: 1
  ckpt_dir: ./checkpoints
  ckpt_name: mobilenetv3_best.pt
