data:
  root: /home/rahim/exp/Data/Agriculture_pest_dataset
  img_size: 224
  resize: 256
  train_frac: 0.70
  val_frac: 0.15
  test_frac: 0.15
  batch_size: 64
  num_workers: 4
  balance_seed: 42
system:
  device: "cuda"
  seed: 42
  fp16: false
train:
  epochs: 10
  lr: 0.0005
  weight_decay: 0.0001
  freeze_backbone: true
  label_smoothing: 0.0
  warmup_epochs: 1
  ckpt_dir: ./checkpoints
  ckpt_name: mobilenetv3_best.pt

# Add to config_train.yaml under corruption_finetune:
corruption_finetune:
  enabled: true
  corruption_prob: 0.7
  severity_range: [1, 4]
  epochs: 8
  lr: 1e-4
  weight_decay: 1e-4
  corruption_types:
    - "gaussian_noise"
    - "motion_blur"
    - "brightness"
    - "contrast"
  clean_prob: 0.3
  ckpt_name: "mobilenetv3_corruption_finetuned.pt"
  warmup_epochs: 1
  
  # Contrastive learning parameters
  contrastive_enabled: true
  contrastive_temperature: 0.07
  contrastive_weight: 0.5
  feature_dim: 128
  contrastive_pairs_per_batch: 0.8