# Evaluation configuration
data:
  img_size: 224
  resize: 256

corruption:
  severities: [1, 2, 3, 4, 5]
  types:
    - gaussian_noise
    - motion_blur
    - brightness
    - contrast
    - rain
    - snow
    - frost
    - fog
    - low_light
    - high_light
    - shadow
    - glare
    - haze
    - mist