# Fixed training configuration with more conservative settings
system:
  device: "cuda"
  seed: 42
  fp16: false

data:
  root: "/home/rahim/exp/Data/Agriculture_pest_dataset"
  img_size: 224
  resize: 256
  batch_size: 16
  num_workers: 0
  train_frac: 0.7
  val_frac: 0.15
  test_frac: 0.15
  balance_seed: 42

train:
  epochs: 15
  lr: 0.0002
  weight_decay: 0.0001
  freeze_backbone: false
  label_smoothing: 0.1
  dropout_rate: 0.2
  ckpt_dir: "./checkpoints"
  ckpt_name: "mobilenetv3_13classes_best_vanilla.pt"

corruption_finetune:
  enabled: true
  contrastive_enabled: true
  epochs: 15
  lr: 0.00005  # Much lower learning rate
  weight_decay: 0.0002
  feature_dim: 256
  
  # More conservative regularization weights
  clean_regularization_weight: 0.3  # Reduced
  consistency_weight: 0.1            # Reduced  
  contrastive_weight: 0.2            # Reduced
  contrastive_temperature: 0.1       # Higher temperature
  
  corruption_prob: 0.3               # Lower corruption probability
  severity_range: [1, 2]             # Start with lower severity
  stages: 3
  epochs_per_stage: 3                # Fewer epochs per stage
  
  ckpt_name: "mobilenetv3_13classes_enhanced_weather_contrastive.pt"