# Vanilla MobileNetV3 training configuration
system:
  device: "cuda"
  seed: 42

data:
  root: "/home/rahim/exp/Data/Agriculture_pest_dataset"
  img_size: 224
  resize: 256
  batch_size: 32
  num_workers: 4
  train_frac: 0.7
  val_frac: 0.15
  test_frac: 0.15
  balance_seed: 42

train:
  epochs: 25
  lr: 0.001
  weight_decay: 0.0001
  freeze_backbone: true
  label_smoothing: 0.1
  dropout_rate: 0.3
  ckpt_dir: "./checkpoints"
  warmup_epochs: 3