# Enhanced Multi-Scale TTA Evaluation Configuration

system:
  device: "cuda"  # cuda or cpu
  seed: 42
  fp16: false

data:
  manifest_path: "./checkpoints/split_manifest.json"
  ckpt_path: "./checkpoints/mobilenetv3_13classes_best_contrastive.pt"
  img_size: 224
  resize: 256
  batch_size: 64
  num_workers: 4

enhanced_tta:
  # Cache configuration
  pos_cache_size: 100
  neg_cache_size: 50
  
  # Feature fusion strategy - using simple concat only
  fusion_strategy: "concat"
  
  # TTA thresholds
  tau_ref: 0.6      # Confidence threshold for applying TTA
  tau_pos: 0.7      # Confidence threshold for adding positive samples
  tau_neg: 0.25      # Confidence threshold for adding negative samples
  
  # Warmup configuration
  warmup_tau_pos: 0.8   # Higher threshold for warmup positive samples
  warmup_tau_neg: 0.2   # Threshold for warmup negative samples
  warmup_samples_per_class: 10  # Target samples per class during warmup
  
  # TTA adjustment weights
  beta: 3.0         # Positive similarity weight
  gamma: 2.0        # Negative similarity weight
  
  # Quality control
  quality_threshold: 0.05  # Minimum quality score for using features
  
  # Batch size for warmup (smaller than main batch size)
  batch_size: 32

evaluation:
  # Corruptions to test
  corruptions:
    - "gaussian_noise"
    - "motion_blur" 
    - "brightness"
    - "contrast"
  
  # Severity levels to test (1=mild, 5=severe)
  severities: [1, 2, 3, 4, 5]
  
  # Results saving
  save_results: true
  results_file: "enhanced_tta_results.json"

output:
  # Additional output settings
  verbose: true
  save_predictions: false
  save_cache_stats: true